### PR TITLE
Prevent IndexOutOfRangeException when Recipe.maxRequirements is modified

### PR DESCRIPTION
**Pull request by ExterminatorX99**

### CODE REVIEW

**Comment by ExterminatorX99** [comment]
@JavidPack

**Comment by JavidPack** [comment]
Yeah, I saw this, it'll have to wait untill I have time to look at everything. From what I remember changing Recipe.maxRequirements was supposed to have other unintended consequences, so it was intentional not to assume it would change. I'll have to find time to double check

**Comment by dougbenham** [comment]
Without this fix, the game freezes if you are using Magic Storage + Recipe Browser + Recursive Craft and you open the crafting interface of Magic Storage and then simultaneously click on an item in the Recipe Browser. Thanks for your hard work @ExterminatorX99.

**Comment by Shadowex3** [comment]
> Without this fix, the game freezes if you are using Magic Storage + Recipe Browser + Recursive Craft and you open the crafting interface of Magic Storage and then simultaneously click on an item in the Recipe Browser. Thanks for your hard work @ExterminatorX99.

Magic Storage definitely makes it easier to trigger the crash however it's not a necessary component. I haven't tried to reproduce it in 1.4 yet but in 1.3 I was able to fairly reliably hang the game's process by viewing the recipe for an item and doubleclicking on the next step it's used to build. There also seemed to be certain items particularly prone to causing the issue by viewing them in recipe browser like the cell phone.

This was the error I got. it's an out of range exception but doesn't seem to reference maxrequirements, unless that's something under the hood not visible in the logs.

It's a real tragedy this and Recursive Crafting seem incompatible, they're both gamechanging QoL additions that frankly deserve to be in the base game.

```
[18:57:26] [1/ERROR] [Terraria]: System.IndexOutOfRangeException: Index was outside the bounds of the array.
at RecipeBrowser.RecipeCatalogueUI.SetRecipe(Int32 index) in RecipeBrowser\RecipeCatalogueUI.cs:line 747
at RecipeBrowser.UIElements.UIRecipeSlot.Click(UIMouseEvent evt) in RecipeBrowser\UIElements\UIRecipeSlot.cs:line 67
at Terraria.UI.UserInterface.Update(GameTime time)
at Terraria.ModLoader.ModHooks.UpdateUI(GameTime gameTime)
at Terraria.Main.DoUpdate(GameTime gameTime)
at DMD<Terraria.Main::Update>(Main , GameTime ) 
```

**Comment by JavidPack** [comment]
well, at this point I won't be changing 1.3 anymore, and it should be fixed in 1.4.

**Pull request closed without merging**
